// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Users.proto

package com.managementapp.transfers;

public final class Users {
  private Users() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccountDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.managementapp.transfers.AccountDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>optional string password = 4;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 4;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional int64 phone = 5;</code>
     */
    long getPhone();

    /**
     * <code>optional .com.managementapp.transfers.AccountDTO.Gender gender = 6;</code>
     */
    int getGenderValue();
    /**
     * <code>optional .com.managementapp.transfers.AccountDTO.Gender gender = 6;</code>
     */
    com.managementapp.transfers.Users.AccountDTO.Gender getGender();

    /**
     * <code>optional int64 register_at = 8;</code>
     */
    long getRegisterAt();

    /**
     * <code>optional int64 last_update_at = 9;</code>
     */
    long getLastUpdateAt();

    /**
     * <code>optional bool is_tutor = 10;</code>
     */
    boolean getIsTutor();
  }
  /**
   * Protobuf type {@code com.managementapp.transfers.AccountDTO}
   */
  public  static final class AccountDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.managementapp.transfers.AccountDTO)
      AccountDTOOrBuilder {
    // Use AccountDTO.newBuilder() to construct.
    private AccountDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccountDTO() {
      id_ = 0L;
      username_ = "";
      email_ = "";
      password_ = "";
      phone_ = 0L;
      gender_ = 0;
      registerAt_ = 0L;
      lastUpdateAt_ = 0L;
      isTutor_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AccountDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 40: {

              phone_ = input.readInt64();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              gender_ = rawValue;
              break;
            }
            case 64: {

              registerAt_ = input.readInt64();
              break;
            }
            case 72: {

              lastUpdateAt_ = input.readInt64();
              break;
            }
            case 80: {

              isTutor_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.managementapp.transfers.Users.internal_static_com_managementapp_transfers_AccountDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.managementapp.transfers.Users.internal_static_com_managementapp_transfers_AccountDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.managementapp.transfers.Users.AccountDTO.class, com.managementapp.transfers.Users.AccountDTO.Builder.class);
    }

    /**
     * Protobuf enum {@code com.managementapp.transfers.AccountDTO.Gender}
     */
    public enum Gender
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Male = 0;</code>
       */
      Male(0),
      /**
       * <code>Female = 1;</code>
       */
      Female(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Male = 0;</code>
       */
      public static final int Male_VALUE = 0;
      /**
       * <code>Female = 1;</code>
       */
      public static final int Female_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Gender valueOf(int value) {
        return forNumber(value);
      }

      public static Gender forNumber(int value) {
        switch (value) {
          case 0: return Male;
          case 1: return Female;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Gender>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Gender> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
              public Gender findValueByNumber(int number) {
                return Gender.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.managementapp.transfers.Users.AccountDTO.getDescriptor().getEnumTypes().get(0);
      }

      private static final Gender[] VALUES = values();

      public static Gender valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Gender(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.managementapp.transfers.AccountDTO.Gender)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object username_;
    /**
     * <code>optional string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 4;
    private volatile java.lang.Object password_;
    /**
     * <code>optional string password = 4;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>optional string password = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 5;
    private long phone_;
    /**
     * <code>optional int64 phone = 5;</code>
     */
    public long getPhone() {
      return phone_;
    }

    public static final int GENDER_FIELD_NUMBER = 6;
    private int gender_;
    /**
     * <code>optional .com.managementapp.transfers.AccountDTO.Gender gender = 6;</code>
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>optional .com.managementapp.transfers.AccountDTO.Gender gender = 6;</code>
     */
    public com.managementapp.transfers.Users.AccountDTO.Gender getGender() {
      com.managementapp.transfers.Users.AccountDTO.Gender result = com.managementapp.transfers.Users.AccountDTO.Gender.valueOf(gender_);
      return result == null ? com.managementapp.transfers.Users.AccountDTO.Gender.UNRECOGNIZED : result;
    }

    public static final int REGISTER_AT_FIELD_NUMBER = 8;
    private long registerAt_;
    /**
     * <code>optional int64 register_at = 8;</code>
     */
    public long getRegisterAt() {
      return registerAt_;
    }

    public static final int LAST_UPDATE_AT_FIELD_NUMBER = 9;
    private long lastUpdateAt_;
    /**
     * <code>optional int64 last_update_at = 9;</code>
     */
    public long getLastUpdateAt() {
      return lastUpdateAt_;
    }

    public static final int IS_TUTOR_FIELD_NUMBER = 10;
    private boolean isTutor_;
    /**
     * <code>optional bool is_tutor = 10;</code>
     */
    public boolean getIsTutor() {
      return isTutor_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, password_);
      }
      if (phone_ != 0L) {
        output.writeInt64(5, phone_);
      }
      if (gender_ != com.managementapp.transfers.Users.AccountDTO.Gender.Male.getNumber()) {
        output.writeEnum(6, gender_);
      }
      if (registerAt_ != 0L) {
        output.writeInt64(8, registerAt_);
      }
      if (lastUpdateAt_ != 0L) {
        output.writeInt64(9, lastUpdateAt_);
      }
      if (isTutor_ != false) {
        output.writeBool(10, isTutor_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, password_);
      }
      if (phone_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, phone_);
      }
      if (gender_ != com.managementapp.transfers.Users.AccountDTO.Gender.Male.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, gender_);
      }
      if (registerAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, registerAt_);
      }
      if (lastUpdateAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, lastUpdateAt_);
      }
      if (isTutor_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, isTutor_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.managementapp.transfers.Users.AccountDTO)) {
        return super.equals(obj);
      }
      com.managementapp.transfers.Users.AccountDTO other = (com.managementapp.transfers.Users.AccountDTO) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && (getPhone()
          == other.getPhone());
      result = result && gender_ == other.gender_;
      result = result && (getRegisterAt()
          == other.getRegisterAt());
      result = result && (getLastUpdateAt()
          == other.getLastUpdateAt());
      result = result && (getIsTutor()
          == other.getIsTutor());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPhone());
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      hash = (37 * hash) + REGISTER_AT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRegisterAt());
      hash = (37 * hash) + LAST_UPDATE_AT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastUpdateAt());
      hash = (37 * hash) + IS_TUTOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsTutor());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.managementapp.transfers.Users.AccountDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.managementapp.transfers.Users.AccountDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.managementapp.transfers.Users.AccountDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.managementapp.transfers.Users.AccountDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.managementapp.transfers.Users.AccountDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.managementapp.transfers.Users.AccountDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.managementapp.transfers.Users.AccountDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.managementapp.transfers.Users.AccountDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.managementapp.transfers.Users.AccountDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.managementapp.transfers.Users.AccountDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.managementapp.transfers.Users.AccountDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.managementapp.transfers.AccountDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.managementapp.transfers.AccountDTO)
        com.managementapp.transfers.Users.AccountDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.managementapp.transfers.Users.internal_static_com_managementapp_transfers_AccountDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.managementapp.transfers.Users.internal_static_com_managementapp_transfers_AccountDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.managementapp.transfers.Users.AccountDTO.class, com.managementapp.transfers.Users.AccountDTO.Builder.class);
      }

      // Construct using com.managementapp.transfers.Users.AccountDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        username_ = "";

        email_ = "";

        password_ = "";

        phone_ = 0L;

        gender_ = 0;

        registerAt_ = 0L;

        lastUpdateAt_ = 0L;

        isTutor_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.managementapp.transfers.Users.internal_static_com_managementapp_transfers_AccountDTO_descriptor;
      }

      public com.managementapp.transfers.Users.AccountDTO getDefaultInstanceForType() {
        return com.managementapp.transfers.Users.AccountDTO.getDefaultInstance();
      }

      public com.managementapp.transfers.Users.AccountDTO build() {
        com.managementapp.transfers.Users.AccountDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.managementapp.transfers.Users.AccountDTO buildPartial() {
        com.managementapp.transfers.Users.AccountDTO result = new com.managementapp.transfers.Users.AccountDTO(this);
        result.id_ = id_;
        result.username_ = username_;
        result.email_ = email_;
        result.password_ = password_;
        result.phone_ = phone_;
        result.gender_ = gender_;
        result.registerAt_ = registerAt_;
        result.lastUpdateAt_ = lastUpdateAt_;
        result.isTutor_ = isTutor_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.managementapp.transfers.Users.AccountDTO) {
          return mergeFrom((com.managementapp.transfers.Users.AccountDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.managementapp.transfers.Users.AccountDTO other) {
        if (other == com.managementapp.transfers.Users.AccountDTO.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (other.getPhone() != 0L) {
          setPhone(other.getPhone());
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (other.getRegisterAt() != 0L) {
          setRegisterAt(other.getRegisterAt());
        }
        if (other.getLastUpdateAt() != 0L) {
          setLastUpdateAt(other.getLastUpdateAt());
        }
        if (other.getIsTutor() != false) {
          setIsTutor(other.getIsTutor());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.managementapp.transfers.Users.AccountDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.managementapp.transfers.Users.AccountDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 4;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private long phone_ ;
      /**
       * <code>optional int64 phone = 5;</code>
       */
      public long getPhone() {
        return phone_;
      }
      /**
       * <code>optional int64 phone = 5;</code>
       */
      public Builder setPhone(long value) {
        
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 phone = 5;</code>
       */
      public Builder clearPhone() {
        
        phone_ = 0L;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <code>optional .com.managementapp.transfers.AccountDTO.Gender gender = 6;</code>
       */
      public int getGenderValue() {
        return gender_;
      }
      /**
       * <code>optional .com.managementapp.transfers.AccountDTO.Gender gender = 6;</code>
       */
      public Builder setGenderValue(int value) {
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.managementapp.transfers.AccountDTO.Gender gender = 6;</code>
       */
      public com.managementapp.transfers.Users.AccountDTO.Gender getGender() {
        com.managementapp.transfers.Users.AccountDTO.Gender result = com.managementapp.transfers.Users.AccountDTO.Gender.valueOf(gender_);
        return result == null ? com.managementapp.transfers.Users.AccountDTO.Gender.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.managementapp.transfers.AccountDTO.Gender gender = 6;</code>
       */
      public Builder setGender(com.managementapp.transfers.Users.AccountDTO.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.managementapp.transfers.AccountDTO.Gender gender = 6;</code>
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private long registerAt_ ;
      /**
       * <code>optional int64 register_at = 8;</code>
       */
      public long getRegisterAt() {
        return registerAt_;
      }
      /**
       * <code>optional int64 register_at = 8;</code>
       */
      public Builder setRegisterAt(long value) {
        
        registerAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 register_at = 8;</code>
       */
      public Builder clearRegisterAt() {
        
        registerAt_ = 0L;
        onChanged();
        return this;
      }

      private long lastUpdateAt_ ;
      /**
       * <code>optional int64 last_update_at = 9;</code>
       */
      public long getLastUpdateAt() {
        return lastUpdateAt_;
      }
      /**
       * <code>optional int64 last_update_at = 9;</code>
       */
      public Builder setLastUpdateAt(long value) {
        
        lastUpdateAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 last_update_at = 9;</code>
       */
      public Builder clearLastUpdateAt() {
        
        lastUpdateAt_ = 0L;
        onChanged();
        return this;
      }

      private boolean isTutor_ ;
      /**
       * <code>optional bool is_tutor = 10;</code>
       */
      public boolean getIsTutor() {
        return isTutor_;
      }
      /**
       * <code>optional bool is_tutor = 10;</code>
       */
      public Builder setIsTutor(boolean value) {
        
        isTutor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_tutor = 10;</code>
       */
      public Builder clearIsTutor() {
        
        isTutor_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.managementapp.transfers.AccountDTO)
    }

    // @@protoc_insertion_point(class_scope:com.managementapp.transfers.AccountDTO)
    private static final com.managementapp.transfers.Users.AccountDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.managementapp.transfers.Users.AccountDTO();
    }

    public static com.managementapp.transfers.Users.AccountDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountDTO>
        PARSER = new com.google.protobuf.AbstractParser<AccountDTO>() {
      public AccountDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AccountDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AccountDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountDTO> getParserForType() {
      return PARSER;
    }

    public com.managementapp.transfers.Users.AccountDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_managementapp_transfers_AccountDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_managementapp_transfers_AccountDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Users.proto\022\033com.managementapp.transfe" +
      "rs\"\371\001\n\nAccountDTO\022\n\n\002id\030\001 \001(\003\022\020\n\010usernam" +
      "e\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\020\n\010password\030\004 \001(\t" +
      "\022\r\n\005phone\030\005 \001(\003\022>\n\006gender\030\006 \001(\0162..com.ma" +
      "nagementapp.transfers.AccountDTO.Gender\022" +
      "\023\n\013register_at\030\010 \001(\003\022\026\n\016last_update_at\030\t" +
      " \001(\003\022\020\n\010is_tutor\030\n \001(\010\"\036\n\006Gender\022\010\n\004Male" +
      "\020\000\022\n\n\006Female\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_managementapp_transfers_AccountDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_managementapp_transfers_AccountDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_managementapp_transfers_AccountDTO_descriptor,
        new java.lang.String[] { "Id", "Username", "Email", "Password", "Phone", "Gender", "RegisterAt", "LastUpdateAt", "IsTutor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
