package com.managementapp.database.models

import java.sql.Blob

import com.managementapp.database.models.Gender.Gender

object Gender extends Enumeration {
  type Gender = Value
  val Male, Female = Value
}

case class Users(
                 username: String,
                 password: String,
                 email: String,
                 id: Long = 0, // id will be auto-generated by mysql, use a dummy number to fill the constructor
                 phone: Option[Long] = None,
                 gender: Option[Gender] = None,
                 registerAt: Long = System.currentTimeMillis(),
                 lastUpdateAt: Long = System.currentTimeMillis(),
                 isTutor: Boolean = false
               )
