# --- !Ups

CREATE TABLE IF NOT EXISTS Users (
  id BIGINT NOT NULL AUTO_INCREMENT,
  username VARCHAR(30) NOT NULL,
  password VARCHAR(40) NOT NULL,
  email VARCHAR(50) NOT NULL,
  phone BIGINT,
  gender ENUM('Male', 'Female'),
  register_at BIGINT NOT NULL,
  last_update_at BIGINT NOT NULL,
  is_tutor BOOL NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Groups (
  id BIGINT NOT NULL AUTO_INCREMENT,
  group_name VARCHAR(30) NOT NULL,
  start_at BIGINT NOT NULL,
  end_at BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Quizes (
  id BIGINT NOT NULL AUTO_INCREMENT,
  quiz_name VARCHAR(30) NOT NULL,
  score INT(3) NOT NULL,
  start_at BIGINT NOT NULL,
  end_at BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS QuizItems (
  id BIGINT NOT NULL AUTO_INCREMENT,
  body TEXT NOT NULL,
  choices TEXT NOT NULL,
  answer VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Schools (
  id BIGINT NOT NULL AUTO_INCREMENT,
  school_name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Images (
  id BIGINT NOT NULL AUTO_INCREMENT,
  file_name VARCHAR(50) NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  file_type VARCHAR(10),
  file_size BIGINT,
  upload_at BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Students (
  user_id BIGINT NOT NULL,
  credits INT(3) NOT NULL,
  birthday DATE,
  school_id BIGINT,
  PRIMARY KEY (user_id),
  FOREIGN KEY (user_id)
  REFERENCES Users (id)
    ON DELETE CASCADE,
  FOREIGN KEY (school_id)
  REFERENCES Schools (id)
    ON DELETE SET NULL
);

# --- !Downs

DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Groups CASCADE;
DROP TABLE IF EXISTS Quizes CASCADE;
DROP TABLE IF EXISTS QuizItems CASCADE;
DROP TABLE IF EXISTS Schools CASCADE;
DROP TABLE IF EXISTS Images CASCADE;
DROP TABLE IF EXISTS Students CASCADE;